### PR TITLE
Add JS API reference link to esdoc

### PR DESCRIPTION
**Pull request by rickmak**
refs SkygearIO/skygear-SDK-JS#112

### CODE REVIEW

**Comment by oursky-travis** [comment]
@rickmak, thanks for your PR! By analyzing the annotation information on this pull request, we identified @ben181231 and @bensonby to be potential reviewers

**Comment by rickmak** [comment]
Seem we want the link to be [Experimental cloud code Javascript support API doc] as suggested by @chpapa

**Comment by rickmak** [comment]
I tried to put up the text and it is too long. I think it will be better to mark the cloudcode is experimental at skygear-SDK-JS README.md ?

**Comment by chpapa** [comment]
Should be both. Since we will announce JS cloudcode is experimental we also
need it on cloudcode docs I think

**Comment by bensonby** [comment]
I am not sure how to put this generated JS API doc now because it contains both the non-cloud JS SDK and the cloud code part.

Since the skygear doc site will be revamped, I believe this current link is a temporary one and will be moved. We will have a "References" page with links to the API Reference doc.

My suggestion for now is to put the label "JS API Reference (beta)" under the "Cloud Code" section of the skygear doc, because the current focus of the API reference is the cloud code. If you prefer, I think we can also put the same link under the JS SDK section, for the API reference of JS SDK (although it contains cloud code too).

BTW do you think "beta" serves the same meaning as "experimental"?

**Comment by chpapa** [comment]
Sounds make sense

**Comment by bensonby** [comment]
Modified as d4eba13 to use the label "JS API Reference (beta)" under cloud code.

**Pull request closed without merging**
