### PR TITLE
Add Index Page

### PR DESCRIPTION
**Pull request by ben181231**
connect #6

### CODE REVIEW

**Comment by rickmak** [comment]
Alignment of document screen shot 2016-04-22 at 12 13 14 pm

Other looks fine to me.

**Comment by ben181231** [comment]
I will update the alignment.

By the way, do you think the way to separate the static data into store is okay?

**Comment by rickmak** [comment]
The store looks okay to me.

**Comment by ben181231** [comment]
@rickmak PR updated.

**Pull request merged**
