### PR TITLE
Remove deployment to staging from master branch

### PR DESCRIPTION
**Pull request by bensonby**
connects #369

I have created a new branch "restructure" for the new doc site, which will be automatically deployed to current staging http://docs-staging.skygear.io.

Therefore the original deployment from "master" branch to the staging site is removed.

### CODE REVIEW

**Comment by oursky-travis** [comment]
@bensonby, thanks for your PR! By analyzing the annotation information on this pull request, we identified @ben181231, @rickmak and @cheungpat to be potential reviewers

**Comment by ben181231** [comment]
@bensonby How is the workflow after removing this?

**Comment by bensonby** [comment]
The restructure branch will not be deployed to production until it's ready. But it will be automatically to docs-staging.skygear.io.

Before the restructure branch is ready for production, doc update will be merged to the master branch first, not on the restructure branch, given that the restructure will have different doc content structure.

I hope there will not be a transition period where doc update needs to be done on both branch.
At a certain point, I believe we will stop updating the old structure doc while keeping it in production. But only update in the restructure branch just before the restructure branch can be deployed to production

**Comment by ben181231** [comment]
So, maybe we can move the staging deployment onto another branch, like `staging`.

**Comment by rickmak** [comment]
I agrees with @ben181231

**Comment by bensonby** [comment]
will keep the existing state, only to deploy upon "staging" branch instead of "master" branch.

The restructure branch will be deployed to a separate bucket

**Comment by ben181231** [comment]
Picked as cffc99b

**Pull request closed without merging**
