### PR TITLE
Revise JS SDK Doc Records & Users & Queries

### PR DESCRIPTION
**Pull request by TakLee96**
1. Merged 4 markdown files into 1 for Records page
2. Revised Users page
3. Revised Queries page (merged 3 markdown files into 1)
4. For the "Enforce const-let-var JS style rules", the commits says so but actually not changing the README or code snippets, due to previous comments made by @rickmak 
5. Rebase to resolve merge conflicts

### CODE REVIEW

**Comment by TakLee96** [comment]
Is it too many commits for one single pull request?

**Comment by rickmak** [comment]
1. Please rebase to current master
2. For merging 3 pages into one page, it is about the menu bugs or intent? The menu bug is fixed at current master. No need to modify the content to avoid the bugs (if it is the case.)

**Comment by TakLee96** [comment]
@rickmak I have just done rebase again to reflect the changes made by @ben181231 and now as you can see there are no more conflicts.

Also for merging 3 pages into one page, because the records page is already merged after @david90 suggested me to do so to make the page look nicer, I think it's consistent to merge queries page as well. So I deleted markdown files and put the content into one single file and updated the links in the json files accordingly. I'm not sure what is the menu bug, is it referring to the empty links?

**Comment by david90** [comment]
We will put a section in the same page for easier navigation.

**Comment by TakLee96** [comment]
@rickmak I guess I will write a more detailed explanation of what I have done to assist your reading, and hopefully we can get the pull request solved today:
- `commit#587ca35` modify package.json to allow building on mac
- `commit#70ca963` modify some h1 to h2 and change title to make sure the title in the menu and the title on the page is the same
- `commit#dc39a6f` modify some wording for sequence section under records page
- `commit#7688121` NO LONGER modify the readme file for the style; it's still here because I did not remove it while doing rebase
- `commit#9a93a93` modify some wording for relations and subscription section under records page
- The above two commits change some const or var to let, they were there before we talked about jslint, so if you think it's unnecessary to change, I can change them back in the next pull request
- `commit#baace45` remove several pages and put their content all into record page; explained in the above two comments
- `commit#0243ddd` modify some wording for user section
- `commit#58301a9` modify some wording for query section and also merge several pages into query page; explained in the above two comments
- `commit#cc03a08` and `commit#5a2aea8` are both fixing bug for code snippets; they should actually be one commit using --amend but it turns out that I pushed to origin before making --amend so I have to keep them both
- `commit#31efc9d` just fix a typo in package.json

**Comment by rickmak** [comment]
I merged, to me. Your last comments in the pull request should be baked into the git commit message.

**Pull request merged**
